project:
  type: book
  output-dir: docs

book:
  title: "BS4019: Discovery and Development of Therapeutic Antibodies"
  author: "Kevin Fo"
  date: "11/01/2023"
  chapters:
    - index.qmd
    - part: "**PART 1 : LECTURES**"
      chapters: 
      - intro.qmd
      - wk2.qmd
      - wk3.qmd
      - wk5.qmd 
      - wk6.qmd
      - wk7.qmd 
      - wk9.qmd
  repo-url: https://github.com/kevfo/BS4019-stuff
  repo-actions: [edit, issue]
  comments:
    hypothesis: true
  reader-mode: true
  page-navigation: true
  sharing: [twitter, facebook]

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

